// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package api

import (
	"github.com/Wenell09/MyStock/internal/category/controller"
	"github.com/Wenell09/MyStock/internal/category/repository"
	"github.com/Wenell09/MyStock/internal/category/service"
	"github.com/Wenell09/MyStock/internal/database"
	controller4 "github.com/Wenell09/MyStock/internal/item/controller"
	repository4 "github.com/Wenell09/MyStock/internal/item/repository"
	service4 "github.com/Wenell09/MyStock/internal/item/service"
	controller3 "github.com/Wenell09/MyStock/internal/supplier/controller"
	repository3 "github.com/Wenell09/MyStock/internal/supplier/repository"
	service3 "github.com/Wenell09/MyStock/internal/supplier/service"
	controller5 "github.com/Wenell09/MyStock/internal/transaction/controller"
	repository5 "github.com/Wenell09/MyStock/internal/transaction/repository"
	service5 "github.com/Wenell09/MyStock/internal/transaction/service"
	controller2 "github.com/Wenell09/MyStock/internal/warehouse/controller"
	repository2 "github.com/Wenell09/MyStock/internal/warehouse/repository"
	service2 "github.com/Wenell09/MyStock/internal/warehouse/service"
	"github.com/go-playground/validator"
	"github.com/gofiber/fiber/v2"
	"github.com/sirupsen/logrus"
)

// Injectors from wire.go:

// Injector
func InitApp() (*fiber.App, error) {
	db := database.DBConnection()
	categoryRepository := repository.NewCategoryRepository(db)
	validate := validator.New()
	categoryService := service.NewCategoryService(categoryRepository, validate)
	logger := logrus.New()
	categoryController := controller.NewCategoryController(categoryService, logger)
	warehouseRepository := repository2.NewWarehouseRepository(db)
	warehouseService := service2.NewWarehouseService(warehouseRepository, validate)
	warehouseController := controller2.NewWarehouseController(warehouseService, logger)
	supplierRepository := repository3.NewSupplierRepository(db)
	supplierService := service3.NewSupplierService(supplierRepository, validate)
	supplierController := controller3.NewSupplierController(supplierService, logger)
	itemRepository := repository4.NewItemRepository(db)
	itemService := service4.NewItemService(itemRepository, categoryRepository, supplierRepository, validate)
	itemController := controller4.NewItemController(itemService, logger)
	transactionRepository := repository5.NewTransactionRepository(db)
	itemWarehouseRepository := repository5.NewItemWarehouseRepository(db)
	transactionService := service5.NewTransactionService(db, transactionRepository, itemRepository, itemWarehouseRepository, warehouseRepository, validate)
	transactionController := controller5.NewTransactionController(transactionService, logger)
	app := NewFiberApp(categoryController, warehouseController, supplierController, itemController, transactionController)
	return app, nil
}
