// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package api

import (
	"github.com/Wenell09/MyStock/internal/category/controller"
	"github.com/Wenell09/MyStock/internal/category/repository"
	"github.com/Wenell09/MyStock/internal/category/service"
	"github.com/Wenell09/MyStock/internal/database"
	"github.com/go-playground/validator"
	"github.com/gofiber/fiber/v2"
	"github.com/google/wire"
	"github.com/sirupsen/logrus"
)

// Injectors from wire.go:

// Injector
func InitApp() (*fiber.App, error) {
	db := database.DBConnection()
	categoryRepository := repository.NewCategoryRepository(db)
	validate := validator.New()
	categoryService := service.NewCategoryService(categoryRepository, validate)
	logger := logrus.New()
	categoryController := controller.NewCategoryController(categoryService, logger)
	app := NewFiberApp(categoryController)
	return app, nil
}

// wire.go:

var categorySet = wire.NewSet(repository.NewCategoryRepository, service.NewCategoryService, controller.NewCategoryController)
